# Generated by Django 3.2.18 on 2023-04-28 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='number_of_people',
        ),
    ]
